// ── ML / MLOps Map · data ─────────────────────────────────
// Art-deco palette: deep navy canvas, gold + pewter accents,
// plus subtle hue differentiation per category.
var CATEGORIES = {
  foundations: { label: "Foundations",         color: "#d4b26a", glyph: "◆" },
  data:        { label: "Data",                color: "#9ec8c2", glyph: "◇" },
  ml:          { label: "Machine Learning",    color: "#c7a876", glyph: "◈" },
  dl:          { label: "Deep Learning",       color: "#b894d4", glyph: "❖" },
  mlops:       { label: "MLOps",               color: "#e0c889", glyph: "◉" },
  ops:         { label: "Infrastructure",      color: "#89a5c4", glyph: "◐" },
  applied:     { label: "Roles & Practice",    color: "#d4a574", glyph: "✦" },
};

// Cross-cutting themes — a topic can belong to several at once.
// Toggled from the header to HIGHLIGHT (not filter) matching leaves.
var TAGS = {
  core:       { label: "Foundational",  hint: "Must-know basics regardless of role",        color: "#d4b26a", glyph: "◆" },
  prod:       { label: "Production",    hint: "Matters when you ship to real users",         color: "#e09b6a", glyph: "⬢" },
  llm:        { label: "LLM-era",       hint: "Modern generative / transformer stack",      color: "#b894d4", glyph: "❖" },
  tabular:    { label: "Tabular",       hint: "Classical data-science / non-deep work",     color: "#9ec8c2", glyph: "◇" },
  research:   { label: "Research-y",    hint: "Deeper, theoretical, often optional",        color: "#89a5c4", glyph: "✦" },
};

// Hierarchical structure: hubs have children (leaf nodes).
// By default only the 7 hubs show — the user expands to reveal detail.
var HUBS = [
  {
    id: "foundations", cat: "foundations", title: "Foundations",
    blurb: "The bedrock skills every data person needs before the fancy stuff.",
    children: [
      { id: "math",    level: 1, title: "Mathematics",
        tags: ["core"],
        blurb: "Vectors, gradients, probability — the vocabulary of ML.",
        topics: ["Linear algebra", "Calculus & chain rule", "Probability", "Information theory"] },
      { id: "python",  level: 1, title: "Python",
        tags: ["core"],
        blurb: "The lingua franca of data science.",
        topics: ["Core syntax", "NumPy / Pandas", "Jupyter", "Packaging & venvs"] },
      { id: "sql",     level: 1, title: "SQL",
        tags: ["core","tabular"],
        blurb: "How you actually get the data.",
        topics: ["JOINs", "Window functions", "CTEs", "Query planning"] },
      { id: "cli",     level: 1, title: "Shell & Git",
        tags: ["core","prod"],
        blurb: "Non-negotiable engineering hygiene.",
        topics: ["bash / zsh", "Git workflows", "SSH", "Makefiles"] },
      { id: "stats",   level: 2, title: "Statistics",
        tags: ["core","tabular","research"],
        blurb: "Reason under uncertainty; avoid fooling yourself.",
        topics: ["Estimation & CIs", "Hypothesis testing", "Bayesian thinking", "Experiment design"] },
    ],
  },
  {
    id: "data", cat: "data", title: "Data",
    blurb: "Wrangling, pipelines, and the plumbing that feeds every model.",
    children: [
      { id: "eda",         level: 1, title: "EDA & Visualization",
        tags: ["core","tabular"],
        blurb: "Look before you model.",
        topics: ["Pandas profiling", "Matplotlib / seaborn", "Plotly", "Outlier detection"] },
      { id: "datawrangle", level: 2, title: "Data Wrangling",
        tags: ["core","tabular"],
        blurb: "Clean, join, reshape — the majority of the job.",
        topics: ["Missing data", "Joins & aggregations", "Feature types", "Dates & time zones"] },
      { id: "pipelines",   level: 2, title: "Pipelines",
        tags: ["prod"],
        blurb: "Move data reliably from source to feature.",
        topics: ["Airflow / Prefect / Dagster", "dbt", "Batch vs streaming", "Idempotency"] },
      { id: "warehouse",   level: 2, title: "Warehouses & Lakes",
        tags: ["prod"],
        blurb: "Where analytics and ML data actually lives.",
        topics: ["Snowflake / BigQuery", "Parquet", "Delta / Iceberg", "Lakehouse patterns"] },
      { id: "bigdata",     level: 3, title: "Big Data",
        tags: ["prod"],
        blurb: "When a laptop isn't enough.",
        topics: ["Spark", "Dask / Ray", "Partitioning", "Shuffle cost"] },
      { id: "streaming",   level: 3, title: "Streaming",
        tags: ["prod"],
        blurb: "Events, not snapshots.",
        topics: ["Kafka", "Flink / Beam", "Windowing", "Exactly-once"] },
    ],
  },
  {
    id: "ml", cat: "ml", title: "Machine Learning",
    blurb: "Classical models, feature engineering, and evaluation.",
    children: [
      { id: "mlfund",     level: 1, title: "ML Fundamentals",
        tags: ["core"],
        blurb: "Bias, variance, and the bitter truths.",
        topics: ["Supervised vs unsupervised", "Train/val/test", "Loss functions", "Regularization"] },
      { id: "classical",  level: 2, title: "Classical Models",
        tags: ["tabular","core"],
        blurb: "Often beats deep learning on tabular data.",
        topics: ["Linear/logistic", "Trees & forests", "SVMs", "k-means, PCA"] },
      { id: "boosting",   level: 2, title: "Gradient Boosting",
        tags: ["tabular","prod"],
        blurb: "The quiet workhorse of industry ML.",
        topics: ["XGBoost", "LightGBM", "CatBoost", "Tabular stack"] },
      { id: "featureng",  level: 2, title: "Feature Engineering",
        tags: ["tabular","core"],
        blurb: "Models learn what you let them see.",
        topics: ["Encoding", "Scaling", "Target encoding", "Selection"],
        subnodes: [
          { id: "fe_encoding",  level: 1, title: "Encoding" },
          { id: "fe_scaling",   level: 1, title: "Scaling" },
          { id: "fe_target",    level: 2, title: "Target Encoding" },
          { id: "fe_selection", level: 2, title: "Selection" },
          { id: "fe_interact",  level: 3, title: "Interactions" },
        ] },
      { id: "evaluation", level: 2, title: "Evaluation",
        tags: ["core","tabular"],
        blurb: "If you can't measure it, you can't ship it.",
        topics: ["Confusion matrix & F1", "ROC / PR", "Calibration", "Cross-validation"],
        subnodes: [
          { id: "ev_f1",     level: 1, title: "Confusion & F1" },
          { id: "ev_roc",    level: 2, title: "ROC / PR" },
          { id: "ev_calib",  level: 2, title: "Calibration" },
          { id: "ev_cv",     level: 2, title: "Cross-validation" },
        ] },
      { id: "timeseries", level: 3, title: "Time Series",
        tags: ["tabular"],
        blurb: "When order matters.",
        topics: ["ARIMA / ETS", "Prophet", "Temporal CV", "Forecast horizons"] },
      { id: "recsys",     level: 3, title: "Recommenders",
        tags: ["prod","research"],
        blurb: "Retrieval and ranking at scale.",
        topics: ["Collaborative filtering", "Two-tower", "Ranking", "Cold start"] },
    ],
  },
  {
    id: "dl", cat: "dl", title: "Deep Learning",
    blurb: "Neural networks, transformers, and generative AI.",
    children: [
      { id: "dlfund", level: 2, title: "Deep Learning Basics",
        tags: ["core","research"],
        blurb: "Backprop and its many disguises.",
        topics: ["Autodiff", "Optimizers", "Regularization", "PyTorch basics"] },
      { id: "cnn",    level: 2, title: "CNNs & Vision",
        tags: ["research"],
        blurb: "Images, segmentation, detection.",
        topics: ["ResNet / EfficientNet", "ViT", "Object detection", "Segmentation"] },
      { id: "rnn",    level: 2, title: "Sequences & Transformers",
        tags: ["research","llm"],
        blurb: "From LSTMs to attention.",
        topics: ["LSTM / GRU", "Attention", "Transformers", "Positional encoding"] },
      { id: "llm",    level: 3, title: "LLMs & Gen AI",
        tags: ["llm"],
        blurb: "The part everyone's talking about.",
        topics: ["Pretraining vs fine-tuning", "RLHF / DPO", "Tokenizers", "Eval harnesses"] },
      { id: "rag",    level: 3, title: "RAG & Agents",
        tags: ["llm","prod"],
        blurb: "Grounding LLMs in your data.",
        topics: ["Embeddings & vector DBs", "Chunking", "Tool use", "RAG evaluation"] },
    ],
  },
  {
    id: "mlops", cat: "mlops", title: "MLOps",
    blurb: "Turning experiments into reliable production systems.",
    children: [
      { id: "mlopsfund",   level: 2, title: "MLOps Foundations",
        tags: ["prod","core"],
        blurb: "From notebook to production.",
        topics: ["ML lifecycle", "Reproducibility", "Three pipelines", "Team topologies"] },
      { id: "expt",        level: 2, title: "Experiment Tracking",
        tags: ["prod"],
        blurb: "Know what you ran and why.",
        topics: ["MLflow", "W&B", "Neptune", "Artifacts"] },
      { id: "registry",    level: 2, title: "Model Registry",
        tags: ["prod"],
        blurb: "Versioned, governed artifacts.",
        topics: ["MLflow Registry", "Stages", "Lineage", "Model cards"] },
      { id: "serving",     level: 2, title: "Model Serving",
        tags: ["prod","llm"],
        blurb: "Real-time, batch, streaming inference.",
        topics: ["FastAPI / BentoML", "Triton", "Batch vs realtime", "gRPC vs REST"] },
      { id: "cicd",        level: 2, title: "CI/CD for ML",
        tags: ["prod"],
        blurb: "Automate the boring, gate the risky.",
        topics: ["GitHub Actions", "DVC", "ML tests", "Continuous training"] },
      { id: "monitoring",  level: 2, title: "Monitoring & Drift",
        tags: ["prod"],
        blurb: "Production models rot — catch it.",
        topics: ["Data drift", "Concept drift", "Evidently / Arize", "Alerting"] },
      { id: "featurestore",level: 3, title: "Feature Stores",
        tags: ["prod"],
        blurb: "Online/offline parity for features.",
        topics: ["Feast", "Tecton", "Point-in-time joins", "Online vs offline"] },
    ],
  },
  {
    id: "ops", cat: "ops", title: "Infrastructure",
    blurb: "The platform layer underneath every ML system.",
    children: [
      { id: "docker", level: 1, title: "Docker",
        tags: ["prod","core"],
        blurb: "Ship the environment, not just the code.",
        topics: ["Dockerfiles", "Layers & caching", "Compose", "Multi-stage"] },
      { id: "cloud",  level: 2, title: "Cloud (AWS / GCP / Azure)",
        tags: ["prod"],
        blurb: "Pick one, learn it deeply.",
        topics: ["IAM & networking", "Object storage", "Managed ML", "Cost guardrails"] },
      { id: "observ", level: 2, title: "Observability",
        tags: ["prod"],
        blurb: "Logs, metrics, traces — for models too.",
        topics: ["Prometheus / Grafana", "OpenTelemetry", "Structured logging", "SLOs"] },
      { id: "k8s",    level: 3, title: "Kubernetes",
        tags: ["prod"],
        blurb: "Where production ML lives.",
        topics: ["Pods & deployments", "Helm", "Kubeflow", "GPU scheduling"] },
      { id: "iac",    level: 3, title: "Infra as Code",
        tags: ["prod"],
        blurb: "Describe infra; don't click it.",
        topics: ["Terraform", "Pulumi", "State", "Secrets"] },
    ],
  },
  {
    id: "applied", cat: "applied", title: "Roles & Practice",
    blurb: "Where all of this lands in a real job.",
    children: [
      { id: "ab",       level: 2, title: "Experimentation",
        tags: ["core","tabular","research"],
        blurb: "A/B tests are how ML gets validated.",
        topics: ["Randomization & power", "Interleaving", "Switchback", "Significance pitfalls"] },
      { id: "ethics",   level: 1, title: "Ethics & Safety",
        tags: ["core","llm"],
        blurb: "Fairness, privacy, and model risk.",
        topics: ["Bias audits", "Differential privacy", "Red-teaming", "Model cards"] },
      { id: "ds_role",  level: 2, title: "→ Data Scientist",
        tags: ["core"],
        blurb: "Insight, experimentation, modeling.",
        topics: ["Business framing", "Storytelling", "Stakeholders", "Portfolio projects"] },
      { id: "mle_role", level: 3, title: "→ ML Engineer",
        tags: ["prod"],
        blurb: "Ship and operate models in production.",
        topics: ["System design", "Serving at scale", "On-call", "Cost / latency tradeoffs"] },
    ],
  },
];

// Flatten helpers
var ALL_NODES = (() => {
  const out = [];
  HUBS.forEach(h => {
    out.push({ ...h, isHub: true });
    h.children.forEach(c => out.push({ ...c, cat: h.cat, parent: h.id, isHub: false }));
  });
  return out;
})();

// Curated learning paths (ids refer to leaves + hubs)
var PATHS = {
  ds:  { label: "Data Scientist",  nodes: ["foundations","math","python","sql","stats","data","eda","datawrangle","ml","mlfund","classical","boosting","evaluation","applied","ab","ds_role"] },
  mle: { label: "ML Engineer",     nodes: ["foundations","python","cli","sql","ml","mlfund","featureng","dl","dlfund","mlops","mlopsfund","cicd","registry","serving","monitoring","ops","docker","cloud","applied","mle_role"] },
  llm: { label: "LLM / Gen AI",    nodes: ["foundations","math","python","ml","mlfund","dl","dlfund","rnn","llm","rag","mlops","serving","monitoring","applied","ethics"] },
};

window.CATEGORIES = CATEGORIES; window.TAGS = TAGS; window.HUBS = HUBS; window.ALL_NODES = ALL_NODES; window.PATHS = PATHS;
