title: "Maciej Kozubal"
description: "Full-stack Data Scientist & MLOps Engineer, former Physicists"
url: "https://maciejkozubal.github.io"
baseurl: ""
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
author:
  name: "Maciej Kozubal, PhD"
  avatar: "/assets/images/avatar.jpg"
  bio: "Full-stack Data Scientist & MLOps Engineer"
  location: "London, UK"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/maciejkozubal"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/maciejkozubal/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:mkoz001@gmail.com"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: false # true
      comments: true
      layout: single
      read_time: true
      search: true
      share: true
      related: true
include:
  - _pages
  - favicon.ico
  - "_includes/head-custom.html"

footer:
  links:
    - label: "GitHub"    
      icon: "fab fa-github" 
      url: "https://github.com/maciejkozubal"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/maciej-kozubal"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:mkoz001@gmail.com"
  show_feed_icon: false 